name: Create Tag

on:
  push:
    branches:
      - 'release-*'
      - 'dk-tagging'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: autotag
      # Note: Do NOT update to 1.1.4, as it's broken for us.
      # https://github.com/ButlerLogic/action-autotag/issues/49
      uses: butlerlogic/action-autotag@1.1.2
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      with:
        tag_prefix: "hs-test-v"
        strategy: regex
        root: ./setup.py
        regex_pattern: "version='(([0-9]+\\.){2}[0-9]+.*)',"
